In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [4]:
dataset = pd.read_csv("online food delivery dataset.csv")

In [8]:
dataset.info()
dataset.head()

<class 'pandas.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    str
 2   Marital Status              388 non-null    str
 3   Occupation                  388 non-null    str
 4   Monthly Income              388 non-null    str
 5   Educational Qualifications  388 non-null    str
 6   Family size                 388 non-null    int64
 7   Customer Type               388 non-null    str
 8   latitude                    388 non-null    float64
 9   longitude                   388 non-null    float64
 10  Pin code                    388 non-null    int64
 11  Output                      388 non-null    str
 12  Feedback                    388 non-null    str
 13  Unnamed: 13                 388 non-null    str
dtypes: float64(2), int64(3), str(9)
memory usage: 42.6 KB

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,Yes

In [9]:
dataset_clean = dataset.drop(columns=["latitude", "longitude", "Pin code", "Output", "Feedback", "Unnamed: 13"])

In [10]:
dataset_clean.info()
dataset_clean.head()

<class 'pandas.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    str
 2   Marital Status              388 non-null    str
 3   Occupation                  388 non-null    str
 4   Monthly Income              388 non-null    str
 5   Educational Qualifications  388 non-null    str
 6   Family size                 388 non-null    int64
 7   Customer Type               388 non-null    str
dtypes: int64(2), str(6)
memory usage: 24.4 KB

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular
3,22,Female,Single,Student,No Income,Graduate,6,Frequent
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent